Task 1
sergey-berezin/s02170502 pull request #1
Opened 2020-10-03 22:06 UTC by justdaniel99

You can see comments in commits below

2020-10-11 19:47 UTC, sergey-berezin requested changes

2020-10-11 19:47 UTC, sergey-berezin commented on ClassLibraryProjects/ImageRecognitionLibrary/Class1.cs
> +        public event EventHandler<KeyEventArgs> KeyDown;
Зачем так сложно? Сделайте метод Stop, который будет вызвать пользователем вашей библиотеки. В обработчике Ctlr+C для консольного приложения или по нажатию на кнопку в GUI.

2020-10-11 20:42 UTC, justdaniel99 commented on ClassLibraryProjects/ImageRecognitionLibrary/Class1.cs
> +        public event EventHandler<KeyEventArgs> KeyDown;
Fixed (Оставлен метод RecognitionStop)

2020-10-12 08:31 UTC, sergey-berezin approved these changes

2020-10-12 08:31 UTC, merged